version: "3.9"
services:
  kitchenware-model:
    image: kitchenware-model:xception_v2
  gateway:
    image: kitchenware-gateway:001
    environment:
      - TF_SERVING_HOST=kitchenware-model:8500
    ports:
      - "9696:9696"